project_id = "gfzumwmvixhpytekoegf"

[auth]
enabled = true
site_url = "http://localhost:3000"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[functions.auto-publish-ad]
verify_jwt = false

[functions.initialize-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = false

[functions.send-contact-message]
verify_jwt = false